"""Generates seadash/runtime/unicode.hpp: the code points Python's str.isprintable() rejects
(which repr() escapes), from the running Python's unicodedata.

    python3 tools/gen_unicode.py      # (rerun when Python's Unicode version moves on)
"""

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "seadash" / "runtime" / "unicode.hpp"

ranges: list[tuple[int, int]] = []
start = None
for cp in range(sys.maxunicode + 1):
    if not chr(cp).isprintable():
        if start is None:
            start = cp
    elif start is not None:
        ranges.append((start, cp - 1))
        start = None
if start is not None:
    ranges.append((start, sys.maxunicode))

rows = []
for i in range(0, len(ranges), 4):
    rows.append("    " + " ".join(f"{{0x{a:X}, 0x{b:X}}}," for a, b in ranges[i:i + 4]))
OUT.write_text(f"""// Generated by tools/gen_unicode.py from Unicode {unicodedata.unidata_version}: don't edit.
#pragma once

#include <algorithm>
#include <utility>

namespace sd::unicode {{

// The code points str.isprintable() rejects (repr() escapes them), as inclusive ranges.
inline constexpr std::pair<char32_t, char32_t> nonprintable[] = {{
{chr(10).join(rows)}
}};

inline bool printable(char32_t c) {{
    auto it = std::upper_bound(std::begin(nonprintable), std::end(nonprintable), c,
                               [](char32_t x, const std::pair<char32_t, char32_t>& r) {{ return x < r.first; }});
    return it == std::begin(nonprintable) || c > std::prev(it)->second;
}}

}}  // namespace sd::unicode
""")
print(f"{OUT}: {len(ranges)} ranges (Unicode {unicodedata.unidata_version})")
